### ISSUE TITLE
[PE-D] Inconsistent filter functions for guests and records

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T13-3/tp#177]
Your filter function for guests uses the OR search while the filter function for records uses AND search, maybe can standardize it to one type of search? As a user, I found it very confusing. Besides that, your UG does not state the type of search implemented for filtering records.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Linxcathyyy/ped#10

**Comment by jianh0ng** [comment]
update ug to explain purpose for AND search
